=== marga8080/lw-fabric/lw-fabric-console/src/main/resources/mongodb/mongodb.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.ccip.com/mongo-config" targetNamespace="http://www.ccip.com/mongo-config">
	<xs:element name="mongo-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mongo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alias">
								<xs:simpleType id="nameType">
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="address">
								<xs:simpleType id="ipType">
									<xs:restriction base="xs:string">
										<xs:minLength value="7"/>
										<xs:maxLength value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="port" type="xs:string" nillable="true"/>
							<xs:element name="dbname">
								<xs:simpleType id="dbNameType">
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="needAuth" type="xs:boolean" minOccurs="0"/>
							<xs:element name="replicaSetSeeds" type="xs:string" minOccurs="0"/>
							<xs:element name="username" type="xs:string" minOccurs="0"/>
							<xs:element name="password" type="xs:string" minOccurs="0"/>
							<xs:element name="connectionsPerHost" type="xs:string" minOccurs="0"/>
							<xs:element name="threadsAllowedToBlockForConnectionMultiplier" type="xs:string" minOccurs="0"/>
							<xs:element name="maxWaitTime" type="xs:string" minOccurs="0"/>
							<xs:element name="connectTimeout" type="xs:string" minOccurs="0"/>
							<xs:element name="socketTimeout" type="xs:string" minOccurs="0"/>
							<xs:element name="autoConnectRetry" type="xs:boolean" minOccurs="0"/>	
							<xs:element name="socketKeepAlive" type="xs:boolean" minOccurs="0"/>						 

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== marga8080/lw-fabric/lw-fabric-console/src/main/resources/mongodb/mongodb.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:mongo-config xmlns:ns1="http://www.ccip.com/mongo-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ccip.com/mongo-config mongodb.xsd">
	<mongo>
        <alias>fabric</alias>
        <address>127.0.0.1</address>
        <port>27017</port>
        <dbname>FabricDB</dbname>
        <needAuth>false</needAuth>
        <replicaSetSeeds></replicaSetSeeds>
        <username>zjszf</username>
        <password>kisw62bmks</password>
        <connectionsPerHost>500</connectionsPerHost>
        <threadsAllowedToBlockForConnectionMultiplier>5000</threadsAllowedToBlockForConnectionMultiplier>
        <maxWaitTime>5000</maxWaitTime>
        <connectTimeout>15000</connectTimeout>
        <socketTimeout>20000</socketTimeout>
        <autoConnectRetry>true</autoConnectRetry>
        <socketKeepAlive>true</socketKeepAlive>
    </mongo>
	
	<mongo>
		<alias>bundle</alias>
		<address>127.0.0.1</address> 
		<port>27017</port>
		<dbname>BundleConfig</dbname>
		<needAuth>false</needAuth>
		<replicaSetSeeds></replicaSetSeeds>
		<username>zjszf</username>
		<password>kisw62bmks</password>
		<connectionsPerHost>500</connectionsPerHost>
		<threadsAllowedToBlockForConnectionMultiplier>5000</threadsAllowedToBlockForConnectionMultiplier>
		<maxWaitTime>5000</maxWaitTime>
		<connectTimeout>15000</connectTimeout>
		<socketTimeout>20000</socketTimeout>
		<autoConnectRetry>true</autoConnectRetry>
		<socketKeepAlive>true</socketKeepAlive>
	</mongo>
	
	<mongo>
		<alias>log</alias>
		<address>127.0.0.1</address> 
		<port>27017</port>
		<dbname>LogDB</dbname>
		<needAuth>false</needAuth>
		<replicaSetSeeds></replicaSetSeeds>
		<username>zjszf</username>
		<password>kisw62bmks</password>
		<connectionsPerHost>500</connectionsPerHost>
		<threadsAllowedToBlockForConnectionMultiplier>5000</threadsAllowedToBlockForConnectionMultiplier>
		<maxWaitTime>5000</maxWaitTime>
		<connectTimeout>15000</connectTimeout>
		<socketTimeout>20000</socketTimeout>
		<autoConnectRetry>true</autoConnectRetry>
		<socketKeepAlive>true</socketKeepAlive>
	</mongo>
	

	
	<mongo>
		<alias>monitor</alias>
		<address>127.0.0.1</address> 
		<port>27017</port>
		<dbname>MonitorDB</dbname>
		<needAuth>false</needAuth>
		<replicaSetSeeds></replicaSetSeeds>
		<username>zjszf</username>
		<password>kisw62bmks</password>
		<connectionsPerHost>500</connectionsPerHost>
		<threadsAllowedToBlockForConnectionMultiplier>5000</threadsAllowedToBlockForConnectionMultiplier>
		<maxWaitTime>5000</maxWaitTime>
		<connectTimeout>15000</connectTimeout>
		<socketTimeout>20000</socketTimeout>
		<autoConnectRetry>true</autoConnectRetry>
		<socketKeepAlive>true</socketKeepAlive>
	</mongo>
	
	<mongo>
		<alias>session</alias>
		<address>127.0.0.1</address> 
		<port>27017</port>
		<dbname>SessionDB</dbname>
		<needAuth>false</needAuth>
		<replicaSetSeeds></replicaSetSeeds>
		<username>zjszf</username>
		<password>kisw62bmks</password>
		<connectionsPerHost>500</connectionsPerHost>
		<threadsAllowedToBlockForConnectionMultiplier>5000</threadsAllowedToBlockForConnectionMultiplier>
		<maxWaitTime>5000</maxWaitTime>
		<connectTimeout>15000</connectTimeout>
		<socketTimeout>20000</socketTimeout>
		<autoConnectRetry>true</autoConnectRetry>
		<socketKeepAlive>true</socketKeepAlive>
	</mongo>
	
</ns1:mongo-config>
